### ISSUE TITLE
Aborted (core dumped).

### ISSUE THREAD

**Issue by lidgnulinux** [selairi/yatbfw#1]
Hello, I'm glad that I found this project, btw when I run `yatbfw` I get this : 
 
```
[ahmad build]$ yatbfw 
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
```

Are there some libraries missing or I need something else ? Thanks.

**Comment by lidgnulinux** [comment]
So, I tried `yatbfw` on some wayland compositors and it seems work fine now

**Comment by selairi** [comment]
If you found a bug, you can launch yatbfw with "--debug" option. The output will helps to debug it.
Thanks.
