### ISSUE TITLE
Tooltips is misplaced.

### ISSUE THREAD

**Issue by lidgnulinux** [selairi/yatbfw#5]
I don't know if this is a normal behaviour but one of my launcher (bottom left) has tooltip shows at bottom right, the second launcher behave normally. Any fix for that ? thanks.

![2022-09-02T16:06:21,971259071+07:00](https://user-images.githubusercontent.com/99301306/188105988-d5b5ed03-da87-41a0-8600-63fb33634e95.png)

**Comment by selairi** [comment]
Would you be so kind as to send me your "yatbfw.json"?

Thanks!

**Comment by lidgnulinux** [comment]
> Would you be so kind as to send me your "yatbfw.json"?
> 
> Thanks!

Sure, here is my [yatbfw.json](https://gist.github.com/c206f253878663d117460ff72eb1103c).

**Comment by selairi** [comment]
Hi, I have just uploaded some changes. Can you test it?

Thanks

**Comment by lidgnulinux** [comment]
I'm testing it rn and woops still same :( .

**Comment by stefonarch** [comment]
I had the same issue with the first launcher on the left (removed the tooltip), still the same with the last commit.

**Comment by selairi** [comment]
I have just upload a fix for this bug. It should work now.

**Comment by lidgnulinux** [comment]
Thanks @selairi , Ill close it now.

**Comment by stefonarch** [comment]
Confirming, thanks!
