### ISSUE TITLE
Launchers spawn yatbfw process

### ISSUE THREAD

**Issue by stefonarch** [selairi/yatbfw#6]
Every click on a launcher create a new shadow process of yatbfw:

![screen_gio_14:45:54_](https://user-images.githubusercontent.com/10681413/189125662-8e52e381-2eee-45ac-ac49-0c2dcb4d6f93.png)

**Comment by selairi** [comment]
My fault. I forgot to catch SIGCHLD signal and zombie process are not removed.

Fixed.

**Comment by stefonarch** [comment]
Nice :)
