### ISSUE TITLE
Clock makes panel going out of sreen

### ISSUE THREAD

**Issue by stefonarch** [selairi/yatbfw#7]
If  "padding zero" is set changes from 9 to 10 (day of today) or 9:30 to 12:20 this happens:
![screen_sab_08:31:25_](https://user-images.githubusercontent.com/10681413/189478066-21c65477-d87d-431f-8f37-2f8dcfef6ffa.png)

Also in normal state clock is real at the border, having  spacers could be an option.

**Comment by selairi** [comment]
Fixed. I have just uploaded a new commit.

Thanks for your help.
